hydra:
  mode: MULTIRUN
  sweeper:
    params:
      lowfid: 0.0

  sweep:
    dir: benchmark/results_kinetic
    subdir: ${hydra.job.override_dirname}


modes: [sf, mf, random]
af_names: [EI, MES]
cost_ratio: 0.1
seeds: 20
budget: 27
lowfid: 0.0
parallel: True
