hydra:
  mode: MULTIRUN
  sweeper:
    params:
      optimizer: single_fidelity_ei, multi_fidelity_ei, multi_fidelity_mes, single_fidelity_mes, multi_fidelity_kg, single_fidelity_kg
      simulation: hartmann
  sweep:
    dir: benchmark_results_hydra/${now:%Y%m%d%H%M%S}_synthetic_benchmark
    subdir: ${hydra.job.override_dirname}

budget: 30
n_repeats: 15
batch_size: 1
init_samples_budget: 0.1
low_fid_samps_ratio: 0.66666
low_fid: 0.2
cost_ratio: 0.1
parallel: True
optimizer: single_fidelity_ei
simulation: hartmann
