hydra:
  mode: MULTIRUN
  sweeper:
    params:
      optimizer: multi_fidelity_ei, multi_fidelity_mes
      simulation: hartmann
      cost_ratio: 0.05, 0.1, 0.2, 0.5
      low_fid_samps_ratio: 0.0, 0.333333, 0.666666
  sweep:
    dir: benchmark_results_hydra/${now:%Y%m%d%H%M%S}_synthetic_sweep
    subdir: ${hydra.job.override_dirname}

budget: 30
n_repeats: 20
batch_size: 1
parallel: True
init_samples_budget: 0.1
low_fid_samps_ratio: 0.6
cost_ratio: 0.1
low_fid: 0.999
optimizer: single_fidelity_ei
simulation: hartmann
